"""
Django settings for apiproject project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ  # เพิ่มบรรทัดนี้

# Initialize environ
env = environ.Env(
    # ตั้งค่าเริ่มต้น - ถ้าไม่เจอใน .env จะใช้ค่านี้
    DEBUG=(bool, False),
    SECRET_KEY=(str, 'django-insecure-=20ju5r-4)!uz17(r73ynop4sbr&9no__v0b-vml@enbd7+cv%'),
    ALLOWED_HOSTS=(str, "202.29.55.217,localhost,api.npu.ac.th"),
    DB_ENGINE=(str, 'django.db.backends.mysql'),
    DB_NAME=(str, 'api'),
    DB_USER=(str, 'admin_e'),
    DB_PASSWORD=(str, '41132834'),
    DB_HOST=(str, '202.29.55.213'),
    DB_PORT=(str, '3306'),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# อ่านไฟล์ .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apiapp',
    'rest_framework',
    'reservapp',
    'rest_framework_simplejwt',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    # 'apiproject.middleware.ResponseTimeMiddleware',  # เพิ่มบรรทัดนี้
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apiproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apiproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # กำหนดจำนวนรายการต่อหน้า (สามารถปรับเปลี่ยนได้ตามต้องการ)

    # การตั้งค่าสำหรับ API v2 (JWT จะถูกใช้เฉพาะใน v2)
    'DEFAULT_AUTHENTICATION_CLASSES_V2': [
    'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    # ปิด Browsable API
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # ปิดบรรทัดนี้
    ],
}

# เพิ่มการตั้งค่า JWT
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365+30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': env('SECRET_KEY'),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# เพิ่มค่าตัวแปรสำหรับใช้ในแอพพลิเคชัน
# LDAP settings
LDAP_SERVER = env('LDAP_SERVER', default='10.0.3.12')
DOMAIN_NAME = env('DOMAIN_NAME', default='NPU.local')

# MikroTik settings
MIKROTIK_HOST = env('MIKROTIK_HOST', default='202.29.55.180')
MIKROTIK_USER = env('MIKROTIK_USER', default='admin_e')
MIKROTIK_PASSWORD = env('MIKROTIK_PASSWORD', default='41132834@ake@1')

# Home Assistant settings
HA_IP = env('HA_IP', default='202.29.55.30')
HA_PORT = env('HA_PORT', default='8123')
HA_TOKEN = env('HA_TOKEN', default='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI1MTA4ZWRmNTU3Yzc0MjA2OTM4Njk3YjU0YTM3NDlmMCIsImlhdCI6MTcyOTk1NDMwMywiZXhwIjoyMDQ1MzE0MzAzfQ.0089Kp8tiXkkVGRweVRyD-pmXdRlJAlsXvyLOCopb7I')

# Walai API settings
WALAI_API_TOKEN = env('WALAI_API_TOKEN', default='3YhnCZzmyr+8HELDMzufoZ6vccyK1KIoAl30SdYhoFLJD8pRV8emesbLSSya2/NgtjY1dMaqzvClDSHFzF4B3A==')
WALAI_API_URL = env('WALAI_API_URL', default='https://opacapi.npu.ac.th/v3/api/GetPublicPatronData')

# ถ้าอยากอนุญาตเฉพาะ localhost:3000
CORS_ALLOWED_ORIGINS = [
    'http://localhost',
    'https://localhost:3000',
    'http://localhost:3000',
    'http://202.29.55.98',
    'https://202.29.55.98',
    'http://edoc-npu.pages.dev',
    'https://edoc-npu.pages.dev',
    'https://rdb.npu.ac.th',
    'http://rdb-npu.pages.dev',
    'https://rdb-npu.pages.dev',
    'https://rdb-npu.kitchanut-r.workers.dev',
    'https://script.google.com',
    'https://arc.npu.ac.th',
    'http://a.npu.world',
    'https://a.npu.world',
    'http://202.29.55.213',
    'https://202.29.55.213',
]

# หรือใช้ regex pattern แทน
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://script\.google\.com$",
    r"^https://script\.google\.com/.*$",  # รองรับ path ต่างๆ
    r"^https://script\.googleusercontent\.com$",
    r"^https://.*\.googleusercontent\.com$",
]

# หรือถ้าต้องการอนุญาตทุก origin ในช่วงพัฒนา (ไม่แนะนำในโหมดโปรดักชัน)
# CORS_ALLOW_ALL_ORIGINS = True

# เพิ่มการอนุญาตส่ง credentials เช่น คุกกี้
CORS_ALLOW_CREDENTIALS = True