# Generated by Django 5.0.7 on 2024-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('student_code', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('prefix_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('level_id', models.IntegerField(blank=True, null=True)),
                ('level_name', models.CharField(blank=True, max_length=50, null=True)),
                ('program_name', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty_name', models.CharField(blank=True, max_length=100, null=True)),
                ('apassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'students_info',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='นักศึกษา', max_length=100),
            preserve_default=False,
        ),
    ]
