# Generated by Django 5.0.7 on 2024-10-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_studentsinfo_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('staffid', models.CharField(db_column='STAFFID', max_length=50, primary_key=True, serialize=False)),
                ('staffcitizenid', models.CharField(blank=True, db_column='STAFFCITIZENID', max_length=13, null=True)),
                ('prefixfullname', models.CharField(blank=True, db_column='PREFIXFULLNAME', max_length=50, null=True)),
                ('staffname', models.CharField(blank=True, db_column='STAFFNAME', max_length=100, null=True)),
                ('staffsurname', models.CharField(blank=True, db_column='STAFFSURNAME', max_length=100, null=True)),
                ('staffbirthdate', models.DateField(blank=True, db_column='STAFFBIRTHDATE', null=True)),
                ('gendernameth', models.CharField(blank=True, db_column='GENDERNAMETH', max_length=50, null=True)),
                ('posnameth', models.CharField(blank=True, db_column='POSNAMETH', max_length=100, null=True)),
                ('stftypename', models.CharField(blank=True, db_column='STFTYPENAME', max_length=100, null=True)),
                ('substftypename', models.CharField(blank=True, db_column='SUBSTFTYPENAME', max_length=100, null=True)),
                ('stfstaname', models.CharField(blank=True, db_column='STFSTANAME', max_length=100, null=True)),
                ('departmentname', models.CharField(blank=True, db_column='DEPARTMENTNAME', max_length=100, null=True)),
            ],
            options={
                'db_table': 'staff_info',
                'managed': False,
            },
        ),
    ]
