# Generated by Django 5.0.7 on 2024-10-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_staffinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userLdap',
            field=models.CharField(max_length=100),
        ),
    ]
