# Generated by Django 5.0.4 on 2026-06-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_alter_userprofile_userldap'),
    ]

    operations = [
        migrations.CreateModel(
            name='BindingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.CharField(default='ldap_auth', max_length=30)),
                ('line_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_ldap', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('success', 'สำเร็จ'), ('fail', 'ไม่สำเร็จ')], db_index=True, max_length=10)),
                ('reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('api_version', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Binding Log',
                'verbose_name_plural': 'Binding Logs',
                'db_table': 'binding_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
