# Generated by Django 5.0.4 on 2026-06-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_bindinglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.CharField(choices=[('obtain', 'ขอใหม่ (login)'), ('refresh', 'ต่ออายุ (refresh)')], default='obtain', max_length=10)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('jti', models.CharField(blank=True, max_length=64, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Token Issue Log',
                'verbose_name_plural': 'Token Issue Logs',
                'db_table': 'token_issue_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
