# Generated by Django 5.0.4 on 2026-06-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_tokenissuelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_user', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True)),
                ('api_version', models.CharField(blank=True, max_length=5, null=True)),
                ('endpoint', models.CharField(db_index=True, max_length=100)),
                ('method', models.CharField(blank=True, max_length=8, null=True)),
                ('target_user', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('http_status', models.IntegerField(blank=True, db_index=True, null=True)),
                ('result', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Access Log',
                'verbose_name_plural': 'API Access Logs',
                'db_table': 'api_access_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
