# Generated by Django 5.0.4 on 2026-06-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_apiaccessarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('seq', models.IntegerField(unique=True)),
                ('assigned_citizen_id', models.CharField(blank=True, db_index=True, max_length=13, null=True)),
                ('assigned_date', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'External Access Code',
                'verbose_name_plural': 'External Access Codes',
                'db_table': 'external_access_code',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMember',
            fields=[
                ('citizen_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'active'), ('revoked', 'revoked')], db_index=True, default='active', max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'External Member',
                'verbose_name_plural': 'External Members',
                'db_table': 'external_member',
                'ordering': ['-registered_at'],
            },
        ),
    ]
