# Generated by Django 5.0.4 on 2026-06-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_externalaccesscode_externalmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmember',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalmember',
            name='approved_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='externalmember',
            name='member_type',
            field=models.CharField(choices=[('daily', 'daily'), ('permanent', 'permanent')], db_index=True, default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='externalmember',
            name='permanent_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='externalmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='external_member_photos/'),
        ),
        migrations.AlterField(
            model_name='externalmember',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('revoked', 'revoked')], db_index=True, default='active', max_length=10),
        ),
    ]
